### ISSUE TITLE
Servicio de capacitaciones

### ISSUE THREAD

**Issue by gsusmab** [gsusmab/capacitate-api#5]
# Capacitaciones 
Las capacitaciones son una lista de cursos disponibles para que el personal docente se pueda capacitar en cierto área de interés. 

### To-Do
- [x]  Crear la `logica` de los `fields`.
- [x]  Crear los `casos de uso`.
- [x]  Crear los `controladores` correspondientes.
- [x]  Crear la estructura SQL de la entidad `capacitaciones`.
