### ISSUE TITLE
Servicio de participantes

### ISSUE THREAD

**Issue by gsusmab** [gsusmab/capacitate-api#7]
# Participantes
Entidad débil `participantes` resultado relación muchos a muchos entre `docentes` y `convocatorias`. Se pretende almacenar los docentes que se encuentran participando en las distintas convocatorias.

### To-Do
- [x]  Crear la `logica` de los `fields`.
- [x]  Crear los `casos de uso`.
- [x]  Crear los `controladores` correspondientes.
- [x]  Crear la estructura SQL de la entidad `capacitaciones`.
