### ISSUE TITLE
Servicio de instructores

### ISSUE THREAD

**Issue by gsusmab** [gsusmab/capacitate-api#8]
# Instructores
Instructores que imparten capacitaciones.

### To-Do
- [x]  Crear la `logica` de los `fields`.
- [x]  Crear los `casos de uso`.
- [x]  Crear los `controladores` correspondientes.
- [x]  Crear la estructura SQL de la entidad `capacitaciones`.
